### ISSUE TITLE
Incorrectly shows the RES command as SET

### ISSUE THREAD

**Issue by Oleg-N-Cher** [rururutan/mdz80#2]
Incorrectly shows the RES command as SET

The sequence "FD CB 01 A6"

Manbow-J Disassembler for Z80.  Version 0.08 shows:

`      set     4,(iy+001H)`

Other disassemblers:

`RES 4, (IY + 1)`

![image](https://github.com/rururutan/mdz80/assets/1090608/ec140c2c-1e9d-403c-9ab3-6908ee076f96)

P. S. "renge" => "range"

**Comment by rururutan** [comment]
Thank you!
I fixed the problem.
